version: "2"
networks:

  default:
    driver: bridge
    
services:
  app:
    image: tobecrazy/tomcat:v1.0
    container_name: tomcat
    ports:
     - "8000:8080"
    networks:
     - default
    volumes:
     - ./export/ROOT:/usr/local/tomcat/webapps/ROOT
    mem_limit: 2G
