version: "2"
networks:

  default:
    driver: bridge
services:
  tomcat1:
    image: tobecrazy/ubuntu-young:latest
    container_name: tomcat1
    ports:
     - "8001:8080"
    networks:
     - default
    volumes:
     - ./export/ROOT:/usr/local/tomcat/webapps/ROOT
    mem_limit: 2G
  tomcat2:
    image: tobecrazy/ubuntu-young:latest
    container_name: tomcat2
    ports:
     - "8002:8080"
    networks:
     - default
    volumes:
     - ./export/ROOT:/usr/local/tomcat/webapps/ROOT
    mem_limit: 2G
  nginx:
    image: tobecrazy/nginx:latest
    container_name: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - tomcat1
      - tomcat2
    ports:
      - "81:80"
